### ISSUE TITLE
开源社官网若干篇文章页面 404

### ISSUE THREAD

**Issue by Soecka** [kaiyuanshe/kaiyuanshe.github.io#217]
- https://kaiyuanshe.cn/article/KCC-Dalian-A-private-brainstorming-session-about-open-source-business
- https://kaiyuanshe.cn/article/My-story-with-COSCon-From-Passerby-A-to-the-Light-of-the-Community

**Comment by Soecka** [comment]
```
r [URIError]: The specified blob does not exist.
    at /workspace/kaiyuanshe.github.io/node_modules/.pnpm/koajax@0.9.4_typescript@5.1.6/node_modules/koajax/dist/index.js:1:8988
    at step (/workspace/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
    at Object.next (/workspace/kaiyuanshe.github.io/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
    at asyncGeneratorStep (/workspace/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.2/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:5:28)
    at _next (/workspace/kaiyuanshe.github.io/node_modules/.pnpm/@swc+helpers@0.5.2/node_modules/@swc/helpers/cjs/_async_to_generator.cjs:23:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  statusText: 'The specified blob does not exist.',
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Content-Length': '215',
    'Content-Type': 'application/xml',
    Date: 'Thu, 12 Oct 2023 06:34:25 GMT',
    Server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
    'X-Ms-Request-Id': '960af69e-a01e-005a-7dd6-fcac94000000',
    'X-Ms-Version': '2009-09-19'
  },
  body: ArrayBuffer {
    [Uint8Contents]: <ef bb bf 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 75 74 66 2d 38 22 3f 3e 3c 45 72 72 6f 72 3e 3c 43 6f 64 65 3e 42 6c 6f 62 4e 6f 74 46 6f 75 6e 64 3c 2f 43 6f 64 65 3e 3c 4d 65 73 73 61 67 65 3e 54 68 65 20 73 70 65 63 69 66 69 65 64 20 62 6c 6f 62 ... 115 more bytes>,
    byteLength: 215
  }
}
[SSR cache] /: 3.864s
{
  data: {
    props: { articles: [Array], activities: [Array], projects: [Array] }
  },
  expiredAt: 1697092957329
}
```

**Comment by TechQuery** [comment]
因为上个月流程超了就没有抓下来，在文库数据库删了再撤销就行了，非代码问题。
